#!/bin/bash
#SBATCH --account=nn4605k
#SBATCH --job-name=cod

#SBATCH --partition=bigmem
#SBATCH --time=1-0:0:0
#SBATCH --ntasks=2 --cpus-per-task=4
#SBATCH --mem-per-cpu=32G

#conda init bash
#conda activate epimapper_lx
conda install --yes --file requirements.txt

